### ISSUE TITLE
バイナリファイルの無視

### ISSUE THREAD

**Issue by 0xBADDCAFE** [mattn/jvgrep#23]
http://linuxjm.sourceforge.jp/html/GNU_grep/man1/grep.1.html

> -I
> バイナリファイルをマッチするデータを含んでいないものとして 処理します。これは --binary-files=without-match オプションと等価です。

上記の該当機能がほしいです。

掲題とは外れますが、もしくは拡張子を複数指定して検索が可能であればやりたいことは満たせるのですが
- 一般的な実装ではなさそう
- 指定の仕方でいい方法が思いつかない

という点があり、提案すべきではないと考えました。

**Comment by 0xBADDCAFE** [comment]
177d092e9f96cba936caf753ee63d3dbaa03675e で `-I` オプションが実装されたので閉じます。
ありがとうございました。

**Comment by mattn** [comment]
問題があったらまたissueお願いします。
