### ISSUE TITLE
never match empty line

### ISSUE THREAD

**Issue by koron** [mattn/jvgrep#32]
Command to match empty lines, won't match any lines.

    $ jvgrep '^$' foo.txt

Because of this check.  https://github.com/mattn/jvgrep/blob/1d69528c42d3383356e602030b7e46962afb9a1a/jvgrep.go#L282-L284

How to fix this?

1.   add an option (ex. `-e`) to match empty lines 
2.   just remove this check

**Comment by koron** [comment]
とりあえずオプション方式を実装してみました。 #33

**Comment by mattn** [comment]
2でおながいします

On 3/30/15, MURAOKA Taro <notifications@github.com> wrote:
> Command to match empty lines, won't match any lines.
>
>     $ jvgrep '^$' foo.txt
>
> Because of this check.
> https://github.com/mattn/jvgrep/blob/1d69528c42d3383356e602030b7e46962afb9a1a/jvgrep.go#L282-L284
>
> How to fix this?
>
> 1.   add an option (ex. `-e`) to match empty lines
> 2.   just remove this check
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/mattn/jvgrep/issues/32


-- 
- Yasuhiro Matsumoto

**Comment by koron** [comment]
あw 2のバージョンも作りますね～

**Comment by mattn** [comment]
うひw grep と同じにしたいです

On 3/30/15, Yasuhiro MATSUMOTO <mattn.jp@gmail.com> wrote:
> 2でおながいします
>
> On 3/30/15, MURAOKA Taro <notifications@github.com> wrote:
>> Command to match empty lines, won't match any lines.
>>
>>     $ jvgrep '^$' foo.txt
>>
>> Because of this check.
>> https://github.com/mattn/jvgrep/blob/1d69528c42d3383356e602030b7e46962afb9a1a/jvgrep.go#L282-L284
>>
>> How to fix this?
>>
>> 1.   add an option (ex. `-e`) to match empty lines
>> 2.   just remove this check
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/mattn/jvgrep/issues/32
>
>
> --
> - Yasuhiro Matsumoto
>


-- 
- Yasuhiro Matsumoto

**Comment by koron** [comment]
ということでよろしくお願いいたします :bow:
