### ISSUE TITLE
UTF-8 text files that contain non-ASCII characters are not matched

### ISSUE THREAD

**Issue by kechako** [mattn/jvgrep#72]
UTF-8 text files that contain non-ASCII characters are not matched when the pattern is ASCII only.
If `--enc=utf-8` option is specified, it matches.

This issue occurs in v5.8.0 or later. It doesn't occur in v5.7.0.

The following is sample.

sample.txt
```text
非 ASCII 文字と
ASCII が
混ざっている
テキスト
```

And if run the following command, it doesn't match.
```console
$ jvgrep ASCII sample.txt
```

**Comment by mattn** [comment]
Thank you!
